Gestor_de_Obras/Gestor_de_Obras/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('obras/', include('obras.urls')),
]

Gestor_de_Obras/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.home,name = 'home_index'),
    path('resumo/',views.resumo_view,name = 'home_resumo'),
    path('sobre/',views.sobre_view,name = 'home_sobre'),
]


Gestor_de_Obras/obras/urls.py
from django.urls import path
from . import views

app_name = "obras"

urlpatterns = [
    path('', views.listar_obras, name='listar_obras'),
    path('criar/', views.criar_obra, name='criar_obra'),
    path('<int:obra_id>/editar/', views.editar_obra, name='editar_obra'),
    path('<int:obra_id>/excluir/', views.excluir_obra, name='excluir_obra'),
    path('buscar-cep/', views.buscar_cep, name='buscar_cep'),

]

Gestor_de_Obras/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.create_user_view, name = 'create_user_view'), #signup_view
    path('login/',views.login_view, name = 'login_view'),
    path('logout/',views.logout_view, name = 'logout_view'),
    path('list/', views.user_list_view, name='list'),

]

Gestor_de_Obras/home/models.py
from django.db import models

# Create your models here.

Gestor_de_Obras/home/views.py


# Create your views here.
from django.shortcuts import render
from django.contrib.auth.models import User
from obras.models import Obra



def resumo_view(request):
    # Obter os últimos 3 usuários criados/modificados
    ultimos_usuarios = User.objects.order_by('-date_joined')[:3]
    # Obter as últimas 3 obras criadas/modificadas
    ultimas_obras = Obra.objects.order_by('-data_modificacao')[:3]

    return render(request, 'home/resumo.html', {
        'ultimos_usuarios': ultimos_usuarios,
        'ultimas_obras': ultimas_obras,
    })


def home(request):
    return render(request, 'home/index.html')


def sobre_view(request):
    return render(request, 'home/sobre.html')



Gestor_de_Obras/home/templates/home/index.html



{% extends 'base.html' %}

{% block title %}Bem-vindo ao Sistema de Gestão de Obras{% endblock %}

{% block content %}
<div class="container text-center mt-5">
    <h1 class="mb-4 text-primary font-weight-bold">Sistema de Gestão de Obras</h1>
    <p class="lead text-muted">
        Organize, acompanhe e gerencie seus projetos de construção em um único lugar, com uma interface simples e eficiente.
    </p>
    <p class="mb-4">
        Descubra como nosso sistema pode ajudar você a economizar tempo e melhorar a eficiência do gerenciamento de suas obras. 
        Simples, rápido e poderoso!
    </p>
    
    <hr class="my-4">

    <h4 class="mt-5 text-secondary">Por que usar nosso sistema?</h4>
    <div class="row justify-content-center mb-4">
        <div class="col-md-8">
            <div class="card shadow-lg mb-4">
                <div class="card-body">
                    <h5 class="card-title text-success">Gerenciamento Simplificado</h5>
                    <p class="card-text">Com nosso sistema, você poderá monitorar todas as etapas da obra em tempo real e tomar decisões de maneira eficiente.</p>
                </div>
            </div>

            <div class="card shadow-lg mb-4">
                <div class="card-body">
                    <h5 class="card-title text-success">Acompanhamento em Tempo Real</h5>
                    <p class="card-text">Acompanhe as modificações, alocação de recursos e atualizações diretamente da plataforma, com relatórios claros e objetivos.</p>
                </div>
            </div>

            <div class="card shadow-lg mb-4">
                <div class="card-body">
                    <h5 class="card-title text-success">Acesso Seguro e Rápido</h5>
                    <p class="card-text">Acesso a qualquer momento e de qualquer lugar. Segurança de ponta para garantir a proteção dos seus dados.</p>
                </div>
            </div>
        </div>
    </div>

    <p class="mt-4">
        E tem mais! Nosso sistema conta com um <strong>bot de assistência</strong> pronto para ajudá-lo. 
        Sempre que tiver dúvidas, basta clicar no ícone do canto inferior direito da tela e começar a conversar com o <strong>Bob, o construtor.</strong>
    </p>
    
    <p class="mt-4 text-muted">
        Seja bem-vindo(a)! Estamos prontos para transformar a forma como você gerencia suas construções.
    </p>
    
    <hr class="my-4">

    <p class="mt-3">
        <small>Para mais informações, entre em contato com nossa equipe de suporte!</small>
    </p>
</div>
{% endblock %}

Gestor_de_Obras/home/templates/home/resumo.html
{% extends 'base.html' %}

{% block title %}Dashboard - Home{% endblock %}

{% block content %}
<div class="container text-center">
    <h1>Bem-vindo, {{ user.username }}!</h1>
    <p>Você está visualizando os últimos usuários cadastrados, além de poder explorar as obras que passaram por modificações recentemente!</p>

    <div class="row">
        <!-- Bloco de Usuários -->
        <div class="col-md-6">
            <h4>Últimos Usuários Cadastrados no Sistema</h4>
            <ul class="list-group">
                {% for usuario in ultimos_usuarios %}
                    <li class="list-group-item">
                        <strong>{{ usuario.username }}</strong> - Criado em {{ usuario.date_joined|date:"d/m/Y" }}
                    </li>
                {% endfor %}
            </ul>
           <!--  <a href="{% url 'users:list' %}" class="btn btn-primary mt-3">Gerenciar Usuários</a> -->
        </div>

        <!-- Bloco de Obras -->
        <div class="col-md-6">
            <h4>Obras modificadas recentemente</h4>
            <ul class="list-group">
                {% for obra in ultimas_obras %}
                    <li class="list-group-item">
                        <strong>{{ obra.nome }}</strong> - Modificada em {{ obra.data_modificacao|date:"d/m/Y" }}
                    </li>
                {% endfor %}
            </ul>
            <a href="{% url 'obras:listar_obras' %}" class="btn btn-primary mt-3">Gerenciar Obras</a>
        </div>
    </div>
</div>
{% endblock %}

Gestor_de_Obras/home/templates/home/sobre.html
{% extends 'base.html' %}

{% block title %}Sobre Nós{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="text-center">
        <h1 class="mb-4">Sobre Nós</h1>
        <p class="lead">
            Bem-vindo ao nosso sistema! Criado com dedicação e paixão, este projeto visa oferecer uma experiência simples, eficiente e acessível para gerenciar obras e engenheiros.
        </p>
    </div>
    <hr class="my-4">
    <div class="row">
        <div class="col-md-6">
            <h3>Nossa Missão</h3>
            <p>
                Fornecer ferramentas intuitivas para ajudar engenheiros a gerenciar obras, equipes e recursos, 
                reduzindo o esforço manual e otimizando o tempo.
            </p>
        </div>
        <div class="col-md-6">
            <h3>Por que Criamos Este Sistema?</h3>
            <p>
                Trata-se de um projeto de avaliação para a disciplina de laboratório de programação do curso de sistema de informações da universidade Cesmac, foi criado com o intuito de desenvoler as habilidades com Django dos alunos.
            </p>
        </div>
    </div>
    <div class="mt-4">
        <h3>Agradecimentos</h3>
        <p>
            Salve Sorriso, estudei pra caramba esses dias, acho que nunca estudei tanto programação como nas ultimas semanas, eu genuinamente estou feliz com o que fiz. Eu vou adicionar mais coisas nas próximas semanas, faz tempo que eu não me sentia grato por programar, espero que continue melhorando.
            Se você puder me falar no que posso melhorar agradeço. 
        </p>
        <p class="text-muted">
            Desenvolvido por <strong>Pedro Lucas</strong>.
        </p>
    </div>
</div>
{% endblock %}