Gestor_de_Obras/Gestor_de_Obras/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('obras/', include('obras.urls')),
]

Gestor_de_Obras/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.home,name = 'home_index'),
    path('resumo/',views.resumo_view,name = 'home_resumo'),
    path('sobre/',views.sobre_view,name = 'home_sobre'),
]


Gestor_de_Obras/obras/urls.py
from django.urls import path
from . import views

app_name = "obras"

urlpatterns = [
    path('', views.listar_obras, name='listar_obras'),
    path('criar/', views.criar_obra, name='criar_obra'),
    path('<int:obra_id>/editar/', views.editar_obra, name='editar_obra'),
    path('<int:obra_id>/excluir/', views.excluir_obra, name='excluir_obra'),
    path('buscar-cep/', views.buscar_cep, name='buscar_cep'),

]

Gestor_de_Obras/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.create_user_view, name = 'create_user_view'), #signup_view
    path('login/',views.login_view, name = 'login_view'),
    path('logout/',views.logout_view, name = 'logout_view'),
    path('list/', views.user_list_view, name='list'),

]

Gestor_de_Obras/templates/partials/navbar_off.html



<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home:home_index' %}">
        <i class="fas fa-home"></i> Homepage
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:home_sobre' %}">
                    <i class="fas fa-info-circle"></i> Sobre
                </a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link btn btn-outline-light mx-1" href="{% url 'users:create_user_view' %}">
                    <i class="fas fa-user-plus"></i> Registro
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link btn btn-outline-light mx-1" href="{% url 'users:login_view' %}">
                    <i class="fas fa-sign-in-alt"></i> Login
                </a>
            </li>
        </ul>
    </div>
</nav>

Gestor_de_Obras/templates/partials/navbar_on.html



<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home:home_index' %}">
        <i class="fas fa-home"></i> Homepage
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:home_resumo' %}">
                    <i class="fas fa-clipboard-list"></i> Resumo
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'obras:listar_obras' %}">
                    <i class="fas fa-clipboard-list"></i> Listar Obras
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:home_sobre' %}">
                    <i class="fas fa-info-circle"></i> Sobre
                </a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link btn btn-outline-light" href="{% url 'users:logout_view' %}">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
            </li>
        </ul>
    </div>
</nav>

Gestor_de_Obras/templates/partials/navbar_onAntiga.html


<nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="{% url 'home:home_index' %}"><i class="fas fa-home"></i> Homepage</a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'obras:listar_obras' %}"><i class="fas fa-info-circle"></i> Listar Obras </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout_view' %}"><i class="fas fa-info-circle"></i> Logout </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home:home_sobre' %}"><i class="fas fa-info-circle"></i> Sobre </a>
            </li>
        </ul>
    </div>
</nav>

